/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAvatar: (typeof import('element-plus/es'))['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: (typeof import('element-plus/es'))['ElCarousel']
    ElCarouselItem: (typeof import('element-plus/es'))['ElCarouselItem']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: (typeof import('element-plus/es'))['ElDropdown']
    ElDropdownItem: (typeof import('element-plus/es'))['ElDropdownItem']
    ElDropdownMenu: (typeof import('element-plus/es'))['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Icon: (typeof import('./src/components/icons/Icon.vue'))['default']
    IconBar: typeof import('./src/components/icons/IconBar.vue')['default']
    IconCommunity: (typeof import('./src/components/icons/IconCommunity.vue'))['default']
    IconDocumentation: (typeof import('./src/components/icons/IconDocumentation.vue'))['default']
    IconEcosystem: (typeof import('./src/components/icons/IconEcosystem.vue'))['default']
    IconSlider: typeof import('./src/components/icons/IconSlider.vue')['default']
    IconSupport: (typeof import('./src/components/icons/IconSupport.vue'))['default']
    IconTooling: (typeof import('./src/components/icons/IconTooling.vue'))['default']
    IconTrophy: typeof import('./src/components/icons/IconTrophy.vue')['default']
    IconUpload: typeof import('./src/components/icons/IconUpload.vue')['default']
    Message: (typeof import('./src/components/Message.vue'))['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: (typeof import('./src/components/TheWelcome.vue'))['default']
    WelcomeItem: (typeof import('./src/components/WelcomeItem.vue'))['default']
  }
}
